# image will be published to ghcr.io/<user>/<name>
name: custom-silverblue
# description will be included in the image's metadata
description: A test for a custom silverblue image with Hyprland built in

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  # List of copr repositories to be used
  - from-file: default-repositories.yml
  # List of custom scripts
  - from-file: default-scripts.yml  
  # List of default rpm-ostree packages
  - from-file: default-packages.yml
  # List of default flatpak packages
  - from-file: default-flatpaks.yml
  # List of fonts to be installed
  - from-file: default-fonts.yml

    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

